apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8see-exporter.fullname" . }}
  labels:
    {{- include "k8see-exporter.labels" . | nindent 4 }}
data:
  {{- range $k,$v := .Values.configuration }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
